# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-12 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc', '0005_auto_20190111_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
