# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc', '0005_auto_20190111_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('img1', models.CharField(max_length=100)),
                ('img2', models.CharField(max_length=100)),
                ('img3', models.CharField(max_length=100)),
                ('img4', models.CharField(max_length=100)),
                ('introduce', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
    ]
