# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-15 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc', '0006_computers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computers',
            name='img1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='computers',
            name='img2',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='computers',
            name='img3',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='computers',
            name='img4',
            field=models.CharField(max_length=500),
        ),
    ]
