# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-15 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc', '0008_auto_20190115_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.CharField(default='https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1547563523328&di=454d5a9af6531d6a5737be1faad62291&imgtype=0&src=http%3A%2F%2Fattach.bbs.miui.com%2Fforum%2F201705%2F24%2F002346yjf4j61jmcepjjzg.jpg', max_length=500),
        ),
    ]
