# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcc', '0009_auto_20190115_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('isselect', models.BooleanField(default=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcc.Computers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lcc.User')),
            ],
        ),
    ]
