# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcc', '0011_auto_20190116_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
